### ISSUE TITLE
Unable to run remotely?

### ISSUE THREAD

**Issue by MarcLaf** [ejsiron/CertWAC#6]
I have WAC installed on a core install of server 2019. Is there any way to run this application from my local machine and point it to WAC through a ps remote session? Or do I need to install it on the same server as WAC? However it being a core install the GUI won't work.

**Comment by ejsiron** [comment]
It does not run remotely, but it will run on a Server Core system. No desktop or Start menu shortcut, obviously, but you can directly run the EXE.

**Comment by MarcLaf** [comment]
Oh very cool, I did not know that. Thanks Eric!
